spring:
  application:
    name: dbdive
  datasource:
    url: jdbc:mysql://localhost:3603/
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root1
    password: PASSWORD

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: MyAppPool