DELETE FROM child10;
DELETE FROM child9;
DELETE FROM child8;
DELETE FROM child7;
DELETE FROM child6;
DELETE FROM child5;
DELETE FROM child4;
DELETE FROM child3;
DELETE FROM child2;
DELETE FROM child1;

DELETE FROM parent1;

DROP TABLE child10;
DROP TABLE child9;
DROP TABLE child8;
DROP TABLE child7;
DROP TABLE child6;
DROP TABLE child5;
DROP TABLE child4;
DROP TABLE child3;
DROP TABLE child2;
DROP TABLE child1;

DROP TABLE parent1;

