DELETE FROM child10;
DELETE FROM child9;
DELETE FROM child8;
DELETE FROM child7;
DELETE FROM child6;
DELETE FROM child5;
DELETE FROM child4;
DELETE FROM child3;
DELETE FROM child2;
DELETE FROM child1;

DELETE FROM parent1;